name: mindia_flutter
description: Pantallas de MindIA (login, privacidad, home) - prototipo visual.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  # Agrega esta sección de assets:
  assets:
    - assets/logo.png